# -*- coding: utf-8 -*-
"""career_recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mGngNvcLBmv2DXh0YxI1Ca74Vqkb9NDi

# 학과·직업 통합 추천기 (순위 점수합 + 키워드 교집합 연계)

**목적**: 커리어넷 학과·직업 상세페이지에서 추출한 TF-IDF 키워드(각 10개)를 기반으로, 학생의 관심 키워드에 부합하는 학과와 직업을 추천하고, 추천 결과 간 키워드 중첩으로 "학과-직업 연계 진로 페어"를 제시한다.

## 추천 알고리즘 개요

### Step 1. 학과 추천 — 키워드 순위 점수합
각 학과의 TOP10 키워드는 TF-IDF 점수 순으로 정렬되어 있다. 학생의 입력 키워드가 학과 키워드와 매칭되면 그 키워드의 순위에 따라 점수를 부여한다.

| 학과 키워드 순위 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
| 점수 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 |

학생 키워드별 점수를 모두 합한 값을 학과의 **점수합**으로 보고, 점수합 내림차순으로 학과를 정렬한다.

### Step 2. 직업 추천 — 동일 방식
직업 코퍼스에 대해서도 동일한 순위 점수합을 적용한다.

### Step 3. 학과-직업 연계 페어
Step 1·2에서 각각 상위 3개씩 추출 → 3×3=9쌍의 학과-직업 페어를 만든다. 각 페어에 대해 학과 TOP10 키워드와 직업 TOP10 키워드의 **교집합 크기**를 계산하고, 교집합이 큰 순서로 정렬해 "진로 연계 페어"를 제시한다.

### 이 방식의 장점
- **설명 가능성**: "○○학과의 1순위 키워드 '로봇'이 매칭되어 11점" 식으로 추천 근거가 명확하다.
- **학과-직업 연계의 이중 확인**: 학생 키워드와도 잘 맞으면서 학과·직업끼리도 의미가 통하는 페어가 자연스럽게 상위에 위치한다.
- **일관된 단위**: 두 단계 모두 키워드 순위 기반이라 결과 해석이 일관된다.

## 0. 환경 설정 (Colab)

Google Drive 마운트 후 데이터 파일 경로를 지정한다. 로컬 실행 시 마운트 셀은 자동으로 건너뛴다.
"""

try:
    from google.colab import drive
    drive.mount('/content/drive')
    DATA_DIR = '/content/drive/MyDrive/career_recommender'  # 본인 경로에 맞게 수정
    IN_COLAB = True
except ImportError:
    DATA_DIR = '.'
    IN_COLAB = False

print(f'데이터 디렉토리: {DATA_DIR}')
print(f'Colab 여부: {IN_COLAB}')

import os
from itertools import product

import numpy as np
import pandas as pd

pd.set_option('display.max_columns', 20)
pd.set_option('display.width', 220)
pd.set_option('display.max_colwidth', 50)

"""## 1. 데이터 로드 및 정제

원본 CSV에는 동일 `id`의 행이 10번씩 중복 포함되어 있어, `drop_duplicates(['id'])`로 정리한다. 키워드 자체는 동일하므로 첫 행만 남기면 된다.
"""

job_path = os.path.join(DATA_DIR, 'job_info_tfidf_top10.csv')
major_path = os.path.join(DATA_DIR, 'major_info_tfidf_top10.csv')

job_raw = pd.read_csv(job_path, encoding='utf-8-sig')
major_raw = pd.read_csv(major_path, encoding='utf-8-sig')
print(f'[원본] 직업: {len(job_raw)}행, 학과: {len(major_raw)}행')

job = job_raw.drop_duplicates(subset=['id']).reset_index(drop=True)
major = major_raw.drop_duplicates(subset=['id']).reset_index(drop=True)
print(f'[중복 제거] 직업: {len(job)}개, 학과: {len(major)}개')

kw_cols = [f'키워드{i}' for i in range(1, 11)]
major.head(3)

"""## 2. 순위별 점수표 정의"""

# 순위별 점수: 1위=11점, 2위=10점, ..., 10위=2점
RANK_SCORES = {rank: 12 - rank for rank in range(1, 11)}
print('순위별 점수표:')
for r, s in RANK_SCORES.items():
    print(f'  {r:>2}위 → {s:>2}점')

"""## 3. Step 1·2 — 순위 점수합 기반 추천 함수

학생의 입력 키워드를 받아 한 코퍼스(학과 또는 직업)에 대해 점수합을 계산한다. 매칭된 키워드 내역도 함께 반환해 추천 근거를 추적할 수 있게 한다.
"""

def rank_score_recommend(user_keywords, df, name_col, top_n=10):
    """순위 점수합 기반 추천

    Args:
        user_keywords (list[str]): 학생 입력 키워드
        df (DataFrame): 학과 또는 직업 데이터프레임 (id, 명칭, 키워드1~10 포함)
        name_col (str): 명칭 컬럼명 ('학과명' 또는 '직업명')
        top_n (int): 반환할 상위 항목 수

    Returns:
        DataFrame: 점수합이 0보다 큰 항목만, 점수합 내림차순으로 상위 top_n개
                   ('id', name_col, 키워드1~10, '점수합', '매칭내역' 컬럼)
    """
    user_set = set(user_keywords)
    scores = []
    matched_descs = []

    for idx in range(len(df)):
        row_score = 0
        row_match = []
        for rank in range(1, 11):
            kw = df.loc[idx, f'키워드{rank}']
            if pd.notna(kw) and kw in user_set:
                pts = RANK_SCORES[rank]
                row_score += pts
                row_match.append(f'{kw}({rank}위·{pts}점)')
        scores.append(row_score)
        matched_descs.append(' / '.join(row_match) if row_match else '')

    result = df[['id', name_col] + kw_cols].copy()
    result['점수합'] = scores
    result['매칭내역'] = matched_descs
    result = result[result['점수합'] > 0].sort_values('점수합', ascending=False).head(top_n)
    return result.reset_index(drop=True)

"""### 3-1. 단일 코퍼스 추천 검증"""

kws = ['로봇', '인공지능', '데이터']

print(f'입력: {kws}\n')
print('📚 학과 추천 Top 5')
tm = rank_score_recommend(kws, major, '학과명', top_n=5)
print(tm[['학과명', '점수합', '매칭내역']].to_string(index=False))

print('\n💼 직업 추천 Top 5')
tj = rank_score_recommend(kws, job, '직업명', top_n=5)
print(tj[['직업명', '점수합', '매칭내역']].to_string(index=False))

"""## 4. Step 3 — 학과 × 직업 연계 페어 (키워드 교집합)

각각 상위 3개씩 뽑아 3×3=9쌍의 페어를 만든 뒤, 학과 TOP10 키워드와 직업 TOP10 키워드의 **교집합 크기**로 정렬한다.

동률이 발생하는 경우 학과 점수합 + 직업 점수합으로 보조 정렬한다 (학생 키워드와의 적합도가 더 높은 쪽이 우선).
"""

def link_major_job(user_keywords, top_n_each=3, top_n_pairs=9):
    """학과×직업 연계 추천: 상위 학과·직업의 키워드 교집합 크기로 정렬

    Args:
        user_keywords (list[str]): 학생 입력 키워드
        top_n_each (int): 각각 추출할 상위 학과/직업 수 (기본 3)
        top_n_pairs (int): 반환할 페어 수 (기본 9 = 3×3 전체)

    Returns:
        (pairs_df, top_majors, top_jobs)
    """
    top_majors = rank_score_recommend(user_keywords, major, '학과명', top_n=top_n_each)
    top_jobs = rank_score_recommend(user_keywords, job, '직업명', top_n=top_n_each)

    if len(top_majors) == 0 or len(top_jobs) == 0:
        return pd.DataFrame(), top_majors, top_jobs

    rows = []
    for mi in range(len(top_majors)):
        m_kws = set(top_majors.loc[mi, kw_cols].dropna().tolist())
        m_name = top_majors.loc[mi, '학과명']
        m_score = top_majors.loc[mi, '점수합']

        for ji in range(len(top_jobs)):
            j_kws = set(top_jobs.loc[ji, kw_cols].dropna().tolist())
            j_name = top_jobs.loc[ji, '직업명']
            j_score = top_jobs.loc[ji, '점수합']

            overlap = m_kws & j_kws
            rows.append({
                '학과명': m_name,
                '학과점수': m_score,
                '직업명': j_name,
                '직업점수': j_score,
                '겹친키워드수': len(overlap),
                '겹친키워드': ', '.join(sorted(overlap)) if overlap else '(없음)',
            })

    pairs = pd.DataFrame(rows)
    pairs['_보조'] = pairs['학과점수'] + pairs['직업점수']
    pairs = pairs.sort_values(['겹친키워드수', '_보조'], ascending=[False, False])
    pairs = pairs.drop(columns=['_보조']).head(top_n_pairs).reset_index(drop=True)
    return pairs, top_majors, top_jobs

"""## 5. 통합 추천 함수 (Step1+2+3)

위 함수들을 묶어 한 번의 호출로 학생 키워드에 대한 전체 추천 결과를 출력한다.
"""

def recommend_career(user_keywords, top_n_each=3, verbose=True):
    """학생 키워드로 학과·직업 추천 + 학과-직업 연계 페어를 출력"""
    pairs, top_majors, top_jobs = link_major_job(
        user_keywords, top_n_each=top_n_each, top_n_pairs=top_n_each * top_n_each
    )

    if not verbose:
        return {'학과': top_majors, '직업': top_jobs, '연계페어': pairs}

    print('=' * 78)
    print(f'입력 키워드: {user_keywords}')
    print('=' * 78)

    if len(top_majors) == 0 and len(top_jobs) == 0:
        print('⚠️ 매칭된 학과·직업이 없습니다. 다른 키워드를 입력해보세요.')
        return {'학과': top_majors, '직업': top_jobs, '연계페어': pairs}

    print(f'\n[Step 1] 📚 추천 학과 Top {top_n_each}')
    if len(top_majors) > 0:
        print(top_majors[['학과명', '점수합', '매칭내역']].to_string(index=False))
    else:
        print('  (매칭 없음)')

    print(f'\n[Step 2] 💼 추천 직업 Top {top_n_each}')
    if len(top_jobs) > 0:
        print(top_jobs[['직업명', '점수합', '매칭내역']].to_string(index=False))
    else:
        print('  (매칭 없음)')

    print(f'\n[Step 3] 🔗 학과-직업 연계 페어 (키워드 교집합 정렬)')
    if len(pairs) > 0:
        print(pairs.to_string(index=False))
    else:
        print('  (페어 생성 불가)')

    return {'학과': top_majors, '직업': top_jobs, '연계페어': pairs}

"""## 5.5 학생 발화 입력 → LLM 키워드 추출

지금까지는 키워드 리스트를 직접 입력했지만, 실제 서비스에서는 학생이 자기 진로 관심사를 자유롭게 글로 풀어쓰는 게 자연스럽다.

**입력 UX**: "내가 원하는 진로는 무엇인가요?"라는 질문에 학생이 텍스트박스에 자유 발화로 답한다.

**키워드 추출 (OpenAI GPT)**: 학생 발화를 GPT에 전달해 진로 관심 키워드를 JSON 형식으로 받는다. 다음 두 가지 처리가 핵심이다.

1. **긍정 표현만 추출**: 학생이 "관심 있다·좋다·하고 싶다" 등으로 표현한 분야의 키워드만 가져온다.
2. **부정 표현은 제외**: "~는 싫다·별로다·하기 싫다" 안에 등장한 단어는 추출에서 빼야 한다. 그렇지 않으면 학생이 "수학은 싫다"고 했는데 "수학"이 추천 점수합에 잡혀 정반대 결과가 나온다.

**API 키 설정**: Colab의 `userdata` 또는 환경변수에서 GPT API 키를 불러온다.
"""

# ===== 학생 발화 입력 → 진로 추천 (예쁜 표 출력) =====
import ipywidgets as widgets
from IPython.display import display, clear_output, HTML

def render_result_html(result):
    if result is None:
        return '<p>⚠️ 결과가 없습니다.</p>'

    kw_info = result.get('추출키워드', {})
    pos = kw_info.get('긍정_키워드', [])
    neg = kw_info.get('부정_제외', [])
    rationale = kw_info.get('근거', '')

    pos_chips = ' '.join(
        f'<span style="background:#dbeafe;color:#1e40af;padding:4px 10px;border-radius:12px;margin:2px;display:inline-block;font-size:13px;font-weight:500;">{k}</span>'
        for k in pos
    )
    neg_chips = ' '.join(
        f'<span style="background:#fee2e2;color:#991b1b;padding:4px 10px;border-radius:12px;margin:2px;display:inline-block;font-size:13px;text-decoration:line-through;">{k}</span>'
        for k in neg
    ) if neg else '<span style="color:#94a3b8;font-size:13px;">(없음)</span>'

    table_style = 'width:100%;border-collapse:collapse;font-size:13px;margin-top:8px;'
    th_style = 'background:#f1f5f9;color:#0f172a;padding:8px 10px;text-align:left;border-bottom:2px solid #cbd5e1;font-weight:600;'
    td_style = 'padding:7px 10px;border-bottom:1px solid #e2e8f0;'

    # 학과 표
    major_df = result['학과']
    major_rows = ''
    for i, row in major_df.iterrows():
        badge = f'<span style="background:#3b82f6;color:white;padding:2px 8px;border-radius:8px;font-size:11px;font-weight:600;">{i+1}</span>'
        major_rows += (
            f'<tr><td style="{td_style}">{badge}</td>'
            f'<td style="{td_style}font-weight:500;">{row["학과명"]}</td>'
            f'<td style="{td_style}text-align:center;font-weight:600;color:#1e40af;">{row["점수합"]}</td>'
            f'<td style="{td_style}color:#64748b;">{row["매칭내역"]}</td></tr>'
        )
    major_table = (
        f'<h4 style="color:#1e40af;margin:18px 0 4px 0;">📚 추천 학과 Top {len(major_df)}</h4>'
        f'<table style="{table_style}"><thead><tr>'
        f'<th style="{th_style}width:50px;">순위</th>'
        f'<th style="{th_style}">학과명</th>'
        f'<th style="{th_style}width:70px;text-align:center;">점수합</th>'
        f'<th style="{th_style}">매칭 내역</th>'
        f'</tr></thead><tbody>{major_rows}</tbody></table>'
    )

    # 직업 표
    job_df = result['직업']
    job_rows = ''
    for i, row in job_df.iterrows():
        badge = f'<span style="background:#10b981;color:white;padding:2px 8px;border-radius:8px;font-size:11px;font-weight:600;">{i+1}</span>'
        job_rows += (
            f'<tr><td style="{td_style}">{badge}</td>'
            f'<td style="{td_style}font-weight:500;">{row["직업명"]}</td>'
            f'<td style="{td_style}text-align:center;font-weight:600;color:#047857;">{row["점수합"]}</td>'
            f'<td style="{td_style}color:#64748b;">{row["매칭내역"]}</td></tr>'
        )
    job_table = (
        f'<h4 style="color:#047857;margin:18px 0 4px 0;">💼 추천 직업 Top {len(job_df)}</h4>'
        f'<table style="{table_style}"><thead><tr>'
        f'<th style="{th_style}width:50px;">순위</th>'
        f'<th style="{th_style}">직업명</th>'
        f'<th style="{th_style}width:70px;text-align:center;">점수합</th>'
        f'<th style="{th_style}">매칭 내역</th>'
        f'</tr></thead><tbody>{job_rows}</tbody></table>'
    )

    # 연계 페어 표
    pair_df = result['연계페어']
    pair_rows = ''
    for _, row in pair_df.iterrows():
        cnt = int(row['겹친키워드수'])
        highlight = 'background:#fef3c7;' if cnt >= 3 else ('opacity:0.5;' if cnt == 0 else '')
        cnt_badge = (
            f'<span style="background:#f59e0b;color:white;padding:2px 8px;border-radius:8px;font-size:11px;font-weight:600;">{cnt}</span>'
            if cnt > 0 else f'<span style="color:#94a3b8;font-size:11px;">0</span>'
        )
        kw_chips = ' '.join(
            f'<span style="background:#fef3c7;color:#92400e;padding:2px 6px;border-radius:6px;margin:1px;display:inline-block;font-size:11px;">{k.strip()}</span>'
            for k in row['겹친키워드'].split(',') if k.strip() and k.strip() != '(없음)'
        ) or '<span style="color:#94a3b8;font-size:12px;">(공통 없음)</span>'
        pair_rows += (
            f'<tr style="{highlight}">'
            f'<td style="{td_style}font-weight:500;">{row["학과명"]}</td>'
            f'<td style="{td_style}color:#94a3b8;text-align:center;">→</td>'
            f'<td style="{td_style}font-weight:500;">{row["직업명"]}</td>'
            f'<td style="{td_style}text-align:center;">{cnt_badge}</td>'
            f'<td style="{td_style}">{kw_chips}</td></tr>'
        )
    pair_table = (
        f'<h4 style="color:#b45309;margin:18px 0 4px 0;">🔗 학과-직업 연계 페어 (키워드 교집합 정렬)</h4>'
        f'<table style="{table_style}"><thead><tr>'
        f'<th style="{th_style}">학과</th>'
        f'<th style="{th_style}width:30px;"></th>'
        f'<th style="{th_style}">직업</th>'
        f'<th style="{th_style}width:70px;text-align:center;">공통수</th>'
        f'<th style="{th_style}">겹친 키워드</th>'
        f'</tr></thead><tbody>{pair_rows}</tbody></table>'
    )

    kw_box = (
        f'<div style="background:#f8fafc;border-left:4px solid #3b82f6;padding:12px 16px;border-radius:6px;margin-bottom:12px;">'
        f'<div style="font-size:13px;color:#475569;margin-bottom:6px;">▶ 추출된 관심 키워드</div>'
        f'<div style="margin-bottom:8px;">{pos_chips}</div>'
        f'<div style="font-size:12px;color:#64748b;margin-top:8px;">제외된 키워드: {neg_chips}</div>'
        f'<div style="font-size:12px;color:#94a3b8;margin-top:6px;font-style:italic;">{rationale}</div>'
        f'</div>'
    )

    return kw_box + major_table + job_table + pair_table


text_area = widgets.Textarea(
    placeholder='예) 저는 로봇과 인공지능 분야에 관심이 많아요. 데이터 분석도 재밌어 보이고, 영업 같은 일은 별로예요.',
    layout=widgets.Layout(width='100%', height='120px'),
)
submit_btn = widgets.Button(description='추천 받기', button_style='primary')
output_area = widgets.Output()


def on_submit(b):
    with output_area:
        clear_output()
        student_text = text_area.value.strip()
        if not student_text:
            display(HTML('<p style="color:#dc2626;">⚠️ 발화를 입력해주세요.</p>'))
            return
        display(HTML('<p style="color:#64748b;">⏳ 키워드 추출 및 추천 중...</p>'))
        result = recommend_from_speech(student_text, top_n_each=3, verbose=False)
        clear_output()
        if result is None:
            display(HTML('<p style="color:#dc2626;">⚠️ 추천 결과를 생성하지 못했습니다.</p>'))
            return
        display(HTML(render_result_html(result)))


submit_btn.on_click(on_submit)
display(widgets.HTML('<h3>내가 원하는 진로는 무엇인가요?</h3>'))
display(text_area, submit_btn, output_area)

# ===== LLM 프롬프트 정의 =====
SYSTEM_PROMPT = """당신은 한국 고등학생의 진로 발화를 분석해 진로 관심사 키워드를 추출하는 도우미입니다.

다음 규칙을 반드시 지켜주세요:

1. 학생이 **긍정적으로 관심을 표현한** 분야·활동·도구·대상의 핵심 키워드만 추출하세요.
2. **부정 표현 안에 등장한 키워드는 반드시 제외**하세요.
   - "~는 싫어요", "~는 별로예요", "~는 하기 싫고", "~는 안 맞아요", "~는 흥미 없어요" 등
   - 예: "디자인은 좋은데 영업은 싫어요" → ['디자인']만 추출, '영업'은 제외
3. 추출된 키워드는 **명사형 단일 단어 또는 짧은 명사구**로 통일하세요.
   - 좋은 예: "로봇", "인공지능", "데이터", "심리상담"
   - 나쁜 예: "로봇을 만드는 것", "재미있는 디자인"
4. 한국 학과·직업 데이터베이스에서 사용하는 표준 용어로 변환하세요.
   - "AI" → "인공지능", "프로그래밍" → "코딩"·"개발", "그림 그리기" → "미술"
5. 키워드는 **3~7개** 사이로 추출하세요.
6. 응답은 반드시 다음 JSON 형식으로만 답하세요. 다른 설명 금지.

{
  "긍정_키워드": ["키워드1", "키워드2", ...],
  "부정_제외": ["제외된키워드1", ...],
  "근거": "한 줄 요약"
}
"""


def build_user_prompt(student_text):
    return f"""다음은 한 학생의 진로 관심사 발화입니다. 위 규칙에 따라 키워드를 추출해주세요.

[학생 발화]
{student_text}
"""

# ===== OpenAI GPT API 호출 =====
# Colab에서 API 키를 불러오는 방법은 두 가지:
#   (1) Colab 'userdata' (시크릿 매니저 - 권장)
#   (2) 환경변수 OPENAI_API_KEY

import json
import re
import os


def get_openai_api_key():
    """Colab userdata 또는 환경변수에서 API 키를 가져온다"""
    if IN_COLAB:
        try:
            from google.colab import userdata
            return userdata.get('OPENAI_API_KEYP')
        except Exception:
            pass
    return os.environ.get('OPENAI_API_KEYP', '')


def call_gpt(student_text, model='gpt-4o-mini', temperature=0.0):
    """학생 발화를 GPT에 전달해 키워드 JSON을 받는다.

    Returns:
        str: GPT의 raw 응답 텍스트
    """
    from openai import OpenAI  # !pip install openai 필요할 수 있음

    client = OpenAI(api_key=get_openai_api_key())
    response = client.chat.completions.create(
        model=model,
        temperature=temperature,
        messages=[
            {'role': 'system', 'content': SYSTEM_PROMPT},
            {'role': 'user', 'content': build_user_prompt(student_text)},
        ],
    )
    return response.choices[0].message.content

# ===== LLM 응답 파싱 =====

def parse_llm_response(response_text):
    """LLM 응답에서 키워드 JSON을 안전하게 파싱한다.

    GPT가 코드블록(```json ... ```)으로 감싸도 정상 처리되도록 한다.
    JSON 파싱 실패 시 정규식으로 키워드 배열만이라도 건진다.
    """
    cleaned = re.sub(r'```json|```', '', response_text).strip()

    try:
        data = json.loads(cleaned)
        return {
            '긍정_키워드': data.get('긍정_키워드', []),
            '부정_제외': data.get('부정_제외', []),
            '근거': data.get('근거', ''),
        }
    except json.JSONDecodeError:
        match = re.search(r'\[(.*?)\]', cleaned, re.DOTALL)
        if match:
            kws = [k.strip().strip('"\\\'') for k in match.group(1).split(',')]
            return {'긍정_키워드': kws, '부정_제외': [], '근거': '(부분 파싱)'}
        return {'긍정_키워드': [], '부정_제외': [], '근거': '(파싱 실패)'}


def extract_keywords_from_speech(student_text, model='gpt-4o-mini'):
    """학생 발화 → GPT 호출 → 키워드 추출 → 파싱 결과 반환"""
    raw = call_gpt(student_text, model=model)
    return parse_llm_response(raw), raw

# ===== 통합 흐름: 학생 발화 → 추천 =====

def recommend_from_speech(student_text, top_n_each=3, model='gpt-4o-mini', verbose=True):
    """학생 발화를 받아 GPT로 키워드 추출 후 학과·직업 연계 추천까지 수행"""
    if verbose:
        print('▶ 학생 발화')
        print(f'  "{student_text}"\n')

    parsed, raw = extract_keywords_from_speech(student_text, model=model)
    keywords = parsed['긍정_키워드']
    excluded = parsed['부정_제외']

    if verbose:
        print(f'▶ GPT 추출 키워드')
        print(f'  긍정: {keywords}')
        print(f'  부정 제외: {excluded}')
        print(f'  근거: {parsed["근거"]}\n')

    if len(keywords) == 0:
        print('⚠️ 추출된 긍정 키워드가 없습니다.')
        return None

    result = recommend_career(keywords, top_n_each=top_n_each, verbose=verbose)
    result['추출키워드'] = parsed
    return result

# ===== 시뮬레이션 (API 키 없어도 검증 가능) =====
# 실제 호출 시에는 recommend_from_speech("학생 발화 텍스트")를 사용하세요.
# 아래는 GPT 호출 결과를 미리 만들어둔 가짜 응답으로 파이프라인 점검용입니다.

mock_cases = [
    {
        'student': '저는 로봇이랑 인공지능에 관심이 많아요. 데이터 분석도 재밌어 보이고요.',
        'gpt_response': '{"긍정_키워드": ["로봇", "인공지능", "데이터"], "부정_제외": [], "근거": "AI/로봇/데이터 분야 관심"}',
    },
    {
        'student': '디자인이나 미술은 정말 좋은데, 수학이랑 코딩은 너무 싫어요.',
        'gpt_response': '{"긍정_키워드": ["디자인", "미술", "창의"], "부정_제외": ["수학", "코딩"], "근거": "예술 관심·이공계 비선호"}',
    },
    {
        'student': '의학이나 생명과학 쪽에 흥미가 있어요. 다만 환자 직접 보는 임상은 좀 부담이고 연구가 좋아요.',
        'gpt_response': '{"긍정_키워드": ["의학", "생명", "연구"], "부정_제외": ["임상"], "근거": "의생명 연구 선호"}',
    },
]

for case in mock_cases:
    print('▶ 학생 발화')
    print(f'  "{case["student"]}"')
    parsed = parse_llm_response(case['gpt_response'])
    print(f'\n▶ (시뮬레이션) GPT 추출 키워드')
    print(f'  긍정: {parsed["긍정_키워드"]}')
    print(f'  부정 제외: {parsed["부정_제외"]}')
    print(f'  근거: {parsed["근거"]}\n')

    if parsed['긍정_키워드']:
        recommend_career(parsed['긍정_키워드'], top_n_each=3, verbose=True)
    print('\n')

# ===== 실제 GPT API 호출 (Colab에서 키 설정 후 주석 해제) =====
!pip install openai --quiet
#
student_text = "내가 원하는 진로는... (학생이 입력한 텍스트)"
result = recommend_from_speech(student_text, top_n_each=3)

"""## 6. 케이스 검증

성격이 다른 입력 4종으로 추천 결과를 점검한다. 학생 입장에서 "납득되는 흐름인가"를 정성적으로 확인한다.
"""

test_cases = [
    ['로봇', '인공지능', '데이터'],   # 이공계 첨단
    ['디자인', '미술', '창의'],       # 예술/디자인
    ['교육', '아동', '심리'],          # 교육/상담
    ['생명', '의학', '연구'],          # 의·생명
]

for kws in test_cases:
    _ = recommend_career(kws, top_n_each=3)
    print('\n')

"""## 7. 진단 도구

### 7-1. OOV(어휘 외) 키워드 점검
학생이 입력한 키워드 중 어떤 단어가 학과·직업 코퍼스에 등장하지 않는지 알려준다. 추천 결과가 빈약할 때 "왜"를 설명할 수 있게 한다.
"""

ALL_KEYWORDS = set()
for col in kw_cols:
    ALL_KEYWORDS.update(major[col].dropna().tolist())
    ALL_KEYWORDS.update(job[col].dropna().tolist())
print(f'전체 키워드 어휘 크기: {len(ALL_KEYWORDS):,}')


def diagnose_input(keywords):
    in_vocab = [k for k in keywords if k in ALL_KEYWORDS]
    oov = [k for k in keywords if k not in ALL_KEYWORDS]
    return {
        '매칭 가능 키워드': in_vocab,
        '매칭 불가능 키워드(OOV)': oov,
        '커버리지': f'{len(in_vocab)}/{len(keywords)}',
    }


for kws in [['로봇', '인공지능', '메타버스', '블록체인'], ['교육', '아동', '심리']]:
    print(f'\n입력 {kws}')
    print(diagnose_input(kws))

"""### 7-2. 키워드 분포 점검
어떤 키워드가 학과·직업에서 자주 등장하는지 확인한다. "임금/포털/피디" 같은 메타데이터성 단어가 많다면 후속 단계에서 불용어 처리를 검토할 필요가 있다.
"""

job_kw_flat = pd.Series(job[kw_cols].values.ravel()).dropna()
major_kw_flat = pd.Series(major[kw_cols].values.ravel()).dropna()

print('▶ 직업 키워드 빈도 TOP 20')
print(job_kw_flat.value_counts().head(20))
print('\n▶ 학과 키워드 빈도 TOP 20')
print(major_kw_flat.value_counts().head(20))

"""## 8. 다음 단계 검토 사항

1. **불용어 처리**: "임금/포털/피디/자료" 등 커리어넷 메타데이터성 단어가 키워드에 섞여 있다. TF-IDF 추출 단계에서 불용어 사전을 적용해 재추출하면 추천 품질이 크게 개선될 것으로 예상된다.
2. **LLM 출력 안정화**: GPT가 가끔 JSON 형식을 어기거나 한국어 데이터베이스 표준어와 다른 단어(예: "AI" 대신 "인공지능"으로 변환되지 않는 경우)를 반환할 수 있다. (a) `response_format={"type": "json_object"}` 옵션 활용, (b) Few-shot 예시 추가, (c) 학과·직업 키워드 사전을 프롬프트에 일부 포함해 표준어 강제, 등으로 보강할 수 있다.
3. **OOV 처리 정책**: GPT가 추출한 키워드 중 학과·직업 어휘에 없는 단어는 매칭 0이 된다. 이때 (a) 학생에게 다시 묻기, (b) 동의어 사전으로 매핑, (c) 임베딩 유사도로 가장 가까운 어휘로 자동 치환 등의 전략을 검토할 필요가 있다.
4. **부정 표현의 범위 처리**: 현재 부정 표현은 키워드 제외에만 사용하지만, 더 적극적으로 "부정 키워드가 많이 등장한 학과/직업의 점수를 감점"하는 방식도 검토 가치가 있다. 단, 학생의 부정적 단어가 학과·직업 키워드와 일치하는 경우가 흔치 않을 수 있으므로 효과 검증이 필요하다.
5. **연계 강도 정규화**: 현재 교집합 "개수"로 정렬하지만, 두 항목이 모두 일반어(예: "교사, 상담")로 이루어진 경우 의미 없는 매칭이 생길 수 있어, 매칭 키워드의 IDF 가중을 부여하는 것도 검토 가치가 있다.
6. **EBSi 통합**: 학생부 키워드(자기소개서, 활동 기록)에서 자동 추출한 키워드를 입력으로 받는 방향으로 확장하면, 어디가 플랫폼 연계 진로 추천 서비스의 한 축이 될 수 있다. 이 경우 LLM은 학생부 텍스트 → 진로 키워드 변환 어댑터 역할을 한다.
7. **평가 체계**: 학과 졸업생의 실제 진로 데이터(EBSi/대교협 보유 자료)와 매칭해, 본 모델의 추천 페어가 실제 진로 패턴을 얼마나 반영하는지 정량 평가할 필요가 있다.
8. **프롬프트 보안**: LLM 입력에 학생의 자유 발화가 들어가므로 프롬프트 인젝션 위험이 있다. 출력 검증(키워드 길이·개수·문자 종류 제한)과 시스템 프롬프트 무력화 시도 차단을 추가해야 한다.
"""